### ISSUE TITLE
Panic due to `assert_by` proof action

### ISSUE THREAD

**Issue by chanheec** [verus-lang/verus-analyzer#3]
Reported by @JayLorch 

> 
> First, I opened https://github.com/verus-lang/verus-systems-code/tree/main/ironfleet-comparison/ironsht. Then, I opened [environment_t.rs](http://environment_t.rs/) and added a trivial bug:
> 
> ```
> proof fn testit()
> {
>     assert(false);
> }
> ```
> 
> 
> The server window shows the following crash:
> 
> ```
> thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', crates/syntax/src/ast/edit_in_place.rs:607:58
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
>    1: core::panicking::panic_fmt
>              at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
>    2: core::panicking::panic
>              at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:111:5
>    3: syntax::ast::edit_in_place::<impl syntax::ast::generated::nodes::AssertExpr>::make_by_keyword
>    4: ide_assists::handlers::assert_by::assert_by
>    5: ide_assists::assists
>    6: std::panicking::try
>    7: ide::Analysis::assists_with_fixes
>    8: rust_analyzer::handlers::handle_code_action
>    9: std::panicking::try
>   10: <F as threadpool::FnBox>::call_box
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> ```

**Comment by parno** [comment]
This appears to be working now.
